#application: gnext18-v2-d90cf
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

libraries:
- name: flask
  version: 0.12

skip_files:
- firebase/
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*\.zip

handlers:
- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: static

- url: .*
  script: main.app
